---
# SPDX-FileCopyrightText: 2024 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

# 'DEBUG', 'INFO', 'WARNING', 'ERROR' or 'CRITICAL'
log_level: 'INFO'

license_list: 'https://raw.githubusercontent.com/spdx/license-list-data/main/json/licenses.json'  # yamllint disable-line rule:line-length

source: './src/hugo'

projects:
  - 'https://github.com/vascoguita/svec.git'
  - 'https://github.com/vascoguita/spec.git'
  - 'https://github.com/vascoguita/fmc-tdc.git'
  - 'https://github.com/vascoguita/fmc-delay-1ns-8cha.git'
  - 'https://github.com/vascoguita/fmc-adc-100m14b4cha.git'

categories:
  - name: 'FMC Carriers'
    description: 'Boards that connect FMC Modules'
    projects:
      - 'svec'
      - 'spec'
  - name: 'FMC Modules'
    description: 'FPGA Mezzanine Cards'
    projects:
      - 'fmc-tdc'
      - 'fmc-delay-1ns-8cha'
      - 'fmc-adc-100m14b4cha'

featured:
  - 'svec'
  - 'spec'

contacts:
  - name: 'Vasco Guita'
    email: 'vasco.guita@cern.ch'
    projects:
      - 'svec'
      - 'spec'
      - 'fmc-tdc'
      - 'fmc-delay-1ns-8cha'
      - 'fmc-adc-100m14b4cha'

